CREATE TABLE scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_type VARCHAR(30) NOT NULL,
    source_value TEXT,

    score INTEGER NOT NULL,

    total_issues INTEGER NOT NULL DEFAULT 0,
    critical_issues INTEGER NOT NULL DEFAULT 0,
    serious_issues INTEGER NOT NULL DEFAULT 0,
    moderate_issues INTEGER NOT NULL DEFAULT 0,
    minor_issues INTEGER NOT NULL DEFAULT 0,

    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_scans_score
        CHECK (score BETWEEN 0 AND 100),

    CONSTRAINT chk_scans_source_type
        CHECK (source_type IN ('HTML', 'URL', 'CSS')),

    CONSTRAINT chk_scans_issue_counts
        CHECK (
            total_issues >= 0
            AND critical_issues >= 0
            AND serious_issues >= 0
            AND moderate_issues >= 0
            AND minor_issues >= 0
        ),

    CONSTRAINT chk_scans_summary_total
        CHECK (
            total_issues =
                critical_issues
                + serious_issues
                + moderate_issues
                + minor_issues
        )
);

CREATE TABLE issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    scan_id BIGINT NOT NULL,

    rule_id VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,

    severity VARCHAR(20) NOT NULL,
    wcag_criterion VARCHAR(50) NOT NULL,

    selector TEXT,
    snippet TEXT,
    recommendation TEXT NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_issues_scan
        FOREIGN KEY (scan_id)
        REFERENCES scans(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_issues_severity
        CHECK (
            severity IN (
                'CRITICAL',
                'SERIOUS',
                'MODERATE',
                'MINOR'
            )
        )
);

CREATE INDEX idx_scans_analyzed_at
    ON scans(analyzed_at DESC);

CREATE INDEX idx_issues_scan_id
    ON issues(scan_id);

CREATE INDEX idx_issues_severity
    ON issues(severity);

CREATE INDEX idx_issues_rule_id
    ON issues(rule_id);